[2024-12-26T15:09:22.337+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-26T15:09:21.757123+00:00 [queued]>
[2024-12-26T15:09:22.340+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-26T15:09:21.757123+00:00 [queued]>
[2024-12-26T15:09:22.340+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-26T15:09:22.340+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-26T15:09:22.340+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-26T15:09:22.344+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): run_currency_exchange_etl> on 2024-12-26 15:09:21.757123+00:00
[2024-12-26T15:09:22.346+0000] {standard_task_runner.py:55} INFO - Started process 64 to run task
[2024-12-26T15:09:22.348+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'run_currency_exchange_etl', 'manual__2024-12-26T15:09:21.757123+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmpjhy923ih']
[2024-12-26T15:09:22.348+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask run_currency_exchange_etl
[2024-12-26T15:09:22.355+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-26T15:09:22.381+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-26T15:09:21.757123+00:00 [running]> on host c764d654a97f
[2024-12-26T15:09:22.407+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_pipeline
AIRFLOW_CTX_TASK_ID=run_currency_exchange_etl
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T15:09:21.757123+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T15:09:21.757123+00:00
[2024-12-26T15:09:22.408+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-26T15:09:22.408+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/currency_exchange_etl.py']
[2024-12-26T15:09:22.412+0000] {subprocess.py:86} INFO - Output:
[2024-12-26T15:09:22.746+0000] {subprocess.py:93} INFO - USD INR 85.234 2024-12-26 UTC 85.2333 85.238
[2024-12-26T15:09:22.747+0000] {subprocess.py:93} INFO - None
[2024-12-26T15:09:22.747+0000] {subprocess.py:93} INFO - Error connecting to the database: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
[2024-12-26T15:09:22.747+0000] {subprocess.py:93} INFO - 	Is the server running locally and accepting connections on that socket?
[2024-12-26T15:09:22.747+0000] {subprocess.py:93} INFO - 
[2024-12-26T15:09:22.760+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-26T15:09:22.768+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-26T15:09:22.770+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=run_currency_exchange_etl, execution_date=20241226T150921, start_date=20241226T150922, end_date=20241226T150922
[2024-12-26T15:09:22.775+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 29 for task run_currency_exchange_etl (Bash command failed. The command returned a non-zero exit code 1.; 64)
[2024-12-26T15:09:22.823+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-26T15:09:22.835+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
